FROM python:3.10

################################################################################
# from https://stackoverflow.com/a/72465422

# Configure Poetry
ENV POETRY_VERSION=1.4.2
ENV POETRY_HOME=/opt/poetry
ENV POETRY_VENV=/opt/poetry-venv
ENV POETRY_CACHE_DIR=/opt/.cache

# Install poetry separated from system interpreter
RUN python3 -m venv $POETRY_VENV \
    && $POETRY_VENV/bin/pip install -U pip setuptools \
    && $POETRY_VENV/bin/pip install poetry==${POETRY_VERSION}

# Add `poetry` to PATH
ENV PATH="${PATH}:${POETRY_VENV}/bin"

WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y \
  build-essential \
  curl
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
COPY poetry.lock pyproject.toml ./
RUN poetry install --no-root

# Run your app
COPY . /app
CMD [ "poetry", "run", "start" ]

# end https://stackoverflow.com/a/72465422
################################################################################
